---
name: "release"

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4
      - name: "build release archive"
        run: |
          git archive --format=tar HEAD | gzip -9 > "dracut-dropbear.tar.gz"
      - uses: actions/setup-node@4
        name: "setup semantic release plugin"
        with:
          cache: npm
          node-version: lts/*
      - name: "publish release"
      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures
      - run: npx semantic-release@21.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
