---
name: "release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions:
      contents: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: "checkout source"
        uses: actions/checkout@v4
      - name: "build release archive"
        run: |
          set -o xtrace
          asset_name="dracut-dropbear-${GITHUB_REF#refs/*/}.tar.gz"
          echo "asset_name=${asset_name}" >> "${GITHUB_ENV}"
          git archive --format=tar HEAD | gzip -9 > "${asset_name}"
      - name: "publish release"
        uses: cb80/pubrel@v0.21.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ${{env.asset_name}}
