---
name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "release on tag push"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout source"
        uses: actions/checkout@v4
      - name: "build release archive"
        run: |
          filename="dracut-dropbear-$(git describe --tags | sed s:v::)"
          git archive --format=tar HEAD | gzip -9 > "${filename}.tar.gz"
      - name: "upload and release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz
